version: '3.2'

services:
  unit:
    env_file: .env
    build: ./app
    entrypoint:
      - ./node_modules/.bin/lab
      - -t
      - '100'
      - test/unit
    environment:
      NODE_OPTIONS: '--inspect=0.0.0.0:8927'
    ports:
      - 8927:8927
  integration:
    env_file: .env
    build: ./app
    entrypoint:
      - ./node_modules/.bin/lab
      - -t
      - '80'
      - test/integration
    environment:
      VCR_MODE: 'playback'
      NODE_OPTIONS: '--inspect=0.0.0.0:8927'
    ports:
      - 8927:8927
  integration_record:
    env_file: .env
    build: ./app
    entrypoint:
      - ./node_modules/.bin/lab
      - test/integration
    environment:
      VCR_MODE: 'record'
      NODE_OPTIONS: '--inspect=0.0.0.0:8927'
    ports:
      - 8927:8927
  api:
    env_file: .env
    build: ./app
    entrypoint:
      - ./node_modules/.bin/lab
      - test/api
    environment:
      NODE_OPTIONS: '--inspect=0.0.0.0:8927'
    ports:
      - 8927:8927
