version: '3.2'

services:
  app:
    env_file: .env
    build: ./app
    depends_on:
      - db
      - redis
    entrypoint:
      - yarn
      - start
    ports:
      - 8925:8925
  db:
    env_file: .env
    image: arangodb
    ports:
      - 8529:8529
    volumes:
      - type: volume
        source: db
        target: /var/lib/arangodb3
        volume:
          nocopy: true
  redis:
    env_file: .env
    build: ./redis
    ports:
      - 6379:6379

volumes:
  db:
